### PR TITLE
pb am am-xenial: install openjdk qa vars

### PR DESCRIPTION
**Pull request by sbreker**
Install openjdk instead of oracle java:
- archivematica playbook
- archivematica-xenial playbook

### CODE REVIEW

**Comment by sevein** [comment]
Should we rely on the defaults instead as suggested in https://github.com/artefactual/deploy-pub/issues/48?

**Comment by hakamine** [comment]
This is similar to #47 (this time applied to the qa yml files instead of the 1.6 yml files). It looks good to me (in #47 we discussed about being explicit in the variable values to avoid ambiguity so I guess it's better to do as the PR proposes?) 👍

**Comment by sevein** [comment]
That makes sense! Explicit is better than implicit. I have to make this more explicit so I remember :D.

**Review by sevein — APPROVED** [review]

**Comment by sevein** [comment]
@sbreker can you delete the branch please?

**Pull request merged**
