### PR TITLE
Dev/digital ocean install instructions

### PR DESCRIPTION
**Pull request by jrwdunham**

### CODE REVIEW

**Comment by jhsimpson** [comment]
:+1: 

This looks good to me.

**Comment by hakamine** [comment]
@jrwdunham @jhsimpson This PR was merged on the mirror (github.com) but not on the official repository (git.artefactual.com). Would you like me to fix?

**Comment by jrwdunham** [comment]
Sure Hector, if you don't mind. Thanks,

Joel

**Comment by hakamine** [comment]
it should be ok now

**Pull request merged**
